sudo: false
language: python
python:
    - 3.5
    - 3.6
install:
  - pip install -r contrib/requirements/requirements-travis.txt
cache:
  - pip
script:
    - tox
after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install pycurl requests && contrib/make_locale; fi
    - coveralls
